// <auto-generated />
using System;
using API_POUPA_FACIL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APIPOUPAFACIL.Migrations
{
    [DbContext(typeof(BaseContext))]
    [Migration("20240810185346_InitialCreateCorrected")]
    partial class InitialCreateCorrected
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API_POUPA_FACIL.Classes.CategoriasGastos", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));

                    b.Property<string>("NomeCategoria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nome_Categoria");

                    b.HasKey("Codigo");

                    b.ToTable("categoria_gastos", (string)null);
                });

            modelBuilder.Entity("API_POUPA_FACIL.Classes.GastosUsuario", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));

                    b.Property<int>("CategoriaCodigo")
                        .HasColumnType("integer")
                        .HasColumnName("Categoria_id");

                    b.Property<string>("DescricaoGasto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Descricao_Gasto");

                    b.Property<int>("UsuarioCodigo")
                        .HasColumnType("integer")
                        .HasColumnName("Usuario_id");

                    b.Property<double>("ValorGasto")
                        .HasColumnType("double precision")
                        .HasColumnName("Valor_Gasto");

                    b.HasKey("Codigo");

                    b.HasIndex("CategoriaCodigo");

                    b.HasIndex("UsuarioCodigo");

                    b.ToTable("gastos_usuario", (string)null);
                });

            modelBuilder.Entity("API_POUPA_FACIL.Classes.RendaAtiva", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));

                    b.Property<string>("RendaDescricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Renda_Descricao");

                    b.Property<int>("UsuarioCodigo")
                        .HasColumnType("integer")
                        .HasColumnName("Usuario_id");

                    b.Property<double>("ValorRenda")
                        .HasColumnType("double precision")
                        .HasColumnName("Valor_Renda");

                    b.HasKey("Codigo");

                    b.HasIndex("UsuarioCodigo");

                    b.ToTable("renda_ativa", (string)null);
                });

            modelBuilder.Entity("API_POUPA_FACIL.Classes.Usuarios", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datacriacao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nomeusuario");

                    b.Property<string>("NumeroTelefone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_telefone");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha");

                    b.HasKey("Codigo");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("API_POUPA_FACIL.Classes.GastosUsuario", b =>
                {
                    b.HasOne("API_POUPA_FACIL.Classes.CategoriasGastos", "CategoriasGastos")
                        .WithMany("GastosUsuario")
                        .HasForeignKey("CategoriaCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_POUPA_FACIL.Classes.Usuarios", "Usuario")
                        .WithMany("GastosUsuario")
                        .HasForeignKey("UsuarioCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriasGastos");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("API_POUPA_FACIL.Classes.RendaAtiva", b =>
                {
                    b.HasOne("API_POUPA_FACIL.Classes.Usuarios", "Usuario")
                        .WithMany("RendasAtiva")
                        .HasForeignKey("UsuarioCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("API_POUPA_FACIL.Classes.CategoriasGastos", b =>
                {
                    b.Navigation("GastosUsuario");
                });

            modelBuilder.Entity("API_POUPA_FACIL.Classes.Usuarios", b =>
                {
                    b.Navigation("GastosUsuario");

                    b.Navigation("RendasAtiva");
                });
#pragma warning restore 612, 618
        }
    }
}
